//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analyzer.Data.CSQL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EPS_Audited
    {
        public int OId { get; set; }
        public int Year { get; set; }
        public int Quarter { get; set; }
        public string COCR { get; set; }
        public string PARQ { get; set; }
        public string LALU { get; set; }
        public string REXP { get; set; }
        public string CCS { get; set; }
    }
}
