//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analyzer.Data.CSQL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EPS_Audited
    {
        public int OId { get; set; }
        public int Year { get; set; }
        public int Quarter { get; set; }
        public Nullable<double> COCR { get; set; }
        public Nullable<double> PARQ { get; set; }
        public Nullable<double> LALU { get; set; }
        public Nullable<double> REXP { get; set; }
        public Nullable<double> CCS { get; set; }
        public Nullable<double> KDL { get; set; }
        public Nullable<double> SOY { get; set; }
        public Nullable<double> HHL { get; set; }
        public Nullable<double> SEYB { get; set; }
        public Nullable<double> CDB { get; set; }
        public Nullable<double> LFIN { get; set; }
        public Nullable<double> LWL { get; set; }
        public Nullable<double> CIND { get; set; }
        public Nullable<double> DIPD { get; set; }
        public Nullable<double> LOLC { get; set; }
        public Nullable<double> NDB { get; set; }
        public Nullable<double> ACL { get; set; }
        public Nullable<double> SAMP { get; set; }
        public Nullable<double> TPL { get; set; }
        public Nullable<double> CFIN { get; set; }
        public Nullable<double> RCL { get; set; }
        public Nullable<double> DIMO { get; set; }
        public Nullable<double> BLI { get; set; }
        public Nullable<double> REG { get; set; }
        public Nullable<double> ALUF { get; set; }
        public Nullable<double> ARPI { get; set; }
        public Nullable<double> HDFC { get; set; }
        public Nullable<double> COLO { get; set; }
        public Nullable<double> VFIN { get; set; }
        public Nullable<double> PMB { get; set; }
        public Nullable<double> CRL { get; set; }
        public Nullable<double> TJL { get; set; }
        public Nullable<double> GRAN { get; set; }
        public Nullable<double> TAFL { get; set; }
        public Nullable<double> UML { get; set; }
        public Nullable<double> HAYL { get; set; }
        public Nullable<double> AAIC { get; set; }
        public Nullable<double> HNB { get; set; }
        public Nullable<double> BRWN { get; set; }
        public Nullable<double> CIC { get; set; }
        public Nullable<double> DIST { get; set; }
        public Nullable<double> LION { get; set; }
        public Nullable<double> LGL { get; set; }
        public Nullable<double> NTB { get; set; }
        public Nullable<double> DFCC { get; set; }
        public Nullable<double> SUN { get; set; }
        public Nullable<double> LLUB { get; set; }
        public Nullable<double> TYRE { get; set; }
        public Nullable<double> ASIR { get; set; }
        public Nullable<double> CARG { get; set; }
        public Nullable<double> LHCL { get; set; }
        public Nullable<double> BFL { get; set; }
        public Nullable<double> NEST { get; set; }
        public Nullable<double> GUAR { get; set; }
        public Nullable<double> CTC { get; set; }
        public Nullable<double> KAPI { get; set; }
        public Nullable<double> JKH { get; set; }
        public Nullable<double> LIOC { get; set; }
        public Nullable<double> CLND { get; set; }
        public Nullable<double> AHUN { get; set; }
        public Nullable<double> TKYO { get; set; }
        public Nullable<double> SPEN { get; set; }
        public Nullable<double> COMB { get; set; }
        public Nullable<double> MELS { get; set; }
        public Nullable<double> SLTL { get; set; }
        public Nullable<double> CTHR { get; set; }
        public Nullable<double> CARS { get; set; }
        public Nullable<double> CINS { get; set; }
        public Nullable<double> AEL { get; set; }
        public Nullable<double> BUKI { get; set; }
        public Nullable<double> AHPL { get; set; }
        public Nullable<double> SINS { get; set; }
    }
}
